GRANT ALL PRIVILEGES ON vehicle.* TO user@localhost identified by '1234';
CREATE TABLE VEHICLE
(
  VEHICLE_NO VARCHAR(10),
  COLOR VARCHAR(10),
  WHEEL INT,
  SEAT INT,
  PRIMARY KEY (VEHICLE_NO)
);

CREATE TABLE COURSE
(
  ID INT(32) AUTO_INCREMENT,
  TITLE VARCHAR(100),
  BEGIN_DATE TIMESTAMP DEFAULT  CURRENT_TIMESTAMP,
  END_DATE TIMESTAMP DEFAULT  CURRENT_TIMESTAMP,
  FEE INT(8),
  PRIMARY KEY (ID)
);

CREATE TABLE BOOK
(
  ISBN VARCHAR(50) NOT NULL,
  BOOK_NAME VARCHAR(100) NOT NULL,
  PRICE INT,
  PRIMARY KEY (ISBN)
);

CREATE TABLE BOOK_STOCK
(
  ISBN VARCHAR(50) NOT NULL,
  STOCK INT NOT NULL,
  PRIMARY KEY (ISBN),
  CHECK (STOCK >=0)
);

CREATE TABLE ACCOUNT
(
  USERNAME VARCHAR(50) NOT NULL,
  BALANCE INT NOT NULL,
  PRIMARY KEY (USERNAME),
  CHECK (BALANCE >=0)
);




